Update :ephemeral
* fix build by ignoring post-install script failures
* force rebuild to enable updating distros

diff --git a/.config/ephemeral/tumbleweed/Dockerfile b/.config/ephemeral/tumbleweed/Dockerfile
--- a/.config/ephemeral/tumbleweed/Dockerfile
+++ b/.config/ephemeral/tumbleweed/Dockerfile
@@ -1,7 +1,14 @@
 FROM opensuse/tumbleweed
 
 # Install useful packages not included in the image by default
-RUN zypper refresh && zypper install -y envsubst git htop man neovim tmux sudo vim wget zsh
+RUN zypper refresh && zypper install -y envsubst git htop man neovim tmux sudo vim wget zsh; \
+  EXIT_CODE=$?; \
+  if [ $EXIT_CODE -eq 107 ]; then \
+      echo "Ignoring zypper exit code 107 (RPM post-script failure in Docker context)"; \
+      exit 0; \
+  else \
+      exit $EXIT_CODE; \
+  fi
 
 ENV LANG=en_US.UTF-8
 ENV LC_ALL=en_US.UTF-8
